service: backend-ecommerce-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    IS_OFFLINE: true
    PORT: ${{ secrets.PORT }}
    NODE_ENV: ${{ secrets.NODE_ENV }}
    MONGODB_URI: ${{ secrets.MONGODB_URI }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
    LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
    RATE_LIMIT_WINDOW_MS: ${{ secrets.RATE_LIMIT_WINDOW_MS }}
    RATE_LIMIT_MAX_REQUESTS: ${{ secrets.RATE_LIMIT_MAX_REQUESTS }}

functions:
  api:
    handler: dist/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any