service: backend-ecommerce-api

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    PORT: ${env:PORT}
    NODE_ENV: ${env:NODE_ENV}
    IS_OFFLINE: ${env:IS_OFFLINE}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    LOG_LEVEL: ${env:LOG_LEVEL}
    RATE_LIMIT_WINDOW_MS: ${env:RATE_LIMIT_WINDOW_MS}
    RATE_LIMIT_MAX_REQUESTS: ${env:RATE_LIMIT_MAX_REQUESTS}
    AWS_REGION: ${env:AWS_REGION}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME, 'shophub-ecommerce-assets'}/*"

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /api/docs
          method: get
      - http:
          path: /api/docs/json
          method: get

package:
  patterns:
    - '!./**'
    - 'src/**'
    - 'node_modules/**'
    - 'package.json'
    - 'tsconfig.json'
  excludeDevDependencies: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true